---
server:
  port: 8080
## session time out needs to be second the below is equal to 30 minutes 
  session:
    timeout: 1800
##contextPath: /SpringBootCRUDApp


welcome.message: Hello !! Welcome To SpringBootCRUDApp
---
spring:
 profiles: local, default
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp

thymeleaf:
  mode: HTML5
  cache: false
  templates_root: src/main/resources/templates/
    
logging:
  config: classpath:local/log4j2.xml
  
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/shalumni
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: dev
 
logging:
  config: classpath:dev/log4j2.xml 
  
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/alumni
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
      
---
spring:
  profiles: prod
  
thymeleaf:
  mode: HTML5
  cache: false
  templates_root: src/main/resources/templates/
  
server:
  port: 80
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
logging:
  config: classpath:prod/log4j2.xml
  
datasource:
  sampleapp:
    url: jdbc:mysql://shalumni.cryglausdl0d.us-east-2.rds.amazonaws.com:3306/shalumni
    userName: root
    password: shalumni
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect     
 
     