---
server:
  port: 8080
  session:
    timeout: 1
  ##contextPath: /SpringBootCRUDApp


welcome.message: Hello Mkyong
---
spring:
  profiles: dev,local, default
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/dogapp
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: validate
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/websystique
    username: myuser
    password: mypassword
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect